version: '3'
services:
    db:
        image: mysql:5.7
        env_file: ./docker/mysql/development.env
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/volumes:/var/lib/mysql  
    redis:
        image: redis:3.0.5
        ports:
            - 6379:6379
    web:
        build: .
        command: /bin/sh -c "rm -f /webapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/webapp
        ports:
            - "3000:3000"
        links:
            - db
            - redis
        env_file: ./docker/mysql/development.env
        tty: true
        stdin_open: true

        