version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: root
        ports:
            - "3306:3306"
    
    redis:
        image: redis:latest
        ports:
            - 6379:6379

    web:
        build: .
        command: rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/webapp
        ports:
            - "3000:3000"
        links:
            - db
            - redis
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
