version: '3'
services:
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql  
  redis:
    image: redis:3.0.5
    ports:
      - 6379:6379
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - web:/webapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    env_file: .env
    tty: true
    stdin_open: true
volumes:
  db:
    driver: 'local'
  web:
    driver: 'local'